- hosts: all
  tasks:
    - name: .bashrcに追記
      ansible.builtin.blockinfile:
        path: /home/isucon/.bashrc
        block: "{{item}}"
        insertafter: EOF
        state: present
      with_file:
        - files/bashrc_prompt.txt

    - name: コマンド実行
      ansible.builtin.command: 
        cmd: exec bash
      register: execution_result

    - name: コマンド実行結果を確認
      ansible.builtin.debug:
        var: execution_result

