- hosts: all
  tasks:
    - name: .bashrcに追記
      ansible.builtin.blockinfile:
        path: /home/isucon/.bashrc
        block: "{{item}}"
        insertafter: EOF
        state: present
      with_file:
        - files/bashrc_prompt.txt

    - name: bash_profileファイルをコピー
      ansible.builtin.copy:
        src: ./files/bash_profile
        dest: /home/isucon/.bash_profile

    - name: コマンド実行
      ansible.builtin.shell:
        cmd: exec bash
      args:
        executable: /bin/bash
      changed_when: no
      register: execution_result

    - name: コマンド実行結果の確認
      ansible.builtin.debug:
        var: execution_result

    - name: vimrcファイルをコピー
      ansible.builtin.copy:
        src: ./files/vimrc
        dest: /home/isucon/.vimrc

    - name: alp_amdのダウンロード
      get_url:
        url: https://github.com/tkuchiki/alp/releases/download/v1.0.20/alp_linux_amd64.tar.gz
        dest: /tmp

    - name: alp_armのダウンロード
      get_url:
        url: https://github.com/tkuchiki/alp/releases/download/v1.0.20/alp_linux_arm64.tar.gz
        dest: /tmp

    - name: amd64のファイルの解凍
      unarchive:
        src: /tmp/alp_linux_amd64.tar.gz
        dest: /tmp
        remote_src: yes
      when:
        ansible_architecture == "x86_64"

    - name: arm64のファイルの解凍
      unarchive:
        src: /tmp/alp_linux_arm64.tar.gz
        dest: /tmp
        remote_src: yes
      when:
        ansible_architecture == "aarch64"

    - name: alpのインストール
      ansible.builtin.shell:
        cmd: sudo install /tmp/alp /usr/local/bin/alp
      changed_when: no
      register: execution_result

    - name: コマンド実行結果の確認
      ansible.builtin.debug:
        var: execution_result

