- hosts: all
  tasks:
    - name: add bashrc
      ansible.builtin.blockinfile:
        path: /home/isucon/.bashrc
        block: "{{item}}"
        insertafter: EOF
        state: present
      with_file:
        - files/bashrc_prompt.txt

