- hosts: all
  tasks:
    - name: add bashrc
      ansible.builtin.blockinfile:
        path: /root/.bashrc
        block: |
          source /home/isucon/ISCON_2024/Ansible/files/git-prompt.sh
          source /home/isucon/ISCON_2024/Ansible/files/git-completion.bash
          GIT_PS1_SHOWDIRTYSTATE=true
          export PS1= '\[\033[32m\]\u@\w\[\033[36m\]$(__git_ps1)\[\033[00m\]\n\$ '
        insertafter: EOF
        state: present

