- hosts: all
  tasks:
    - name: .bashrcに追記
      ansible.builtin.blockinfile:
        path: /home/isucon/.bashrc
        block: "{{item}}"
        insertafter: EOF
        state: present
      with_file:
        - files/bashrc_prompt.txt

    - name: bash_profileファイルをコピー
      ansible.builtin.copy:
        src: ./files/bash_profile
        dest: /home/isucon/.bash_profile

    - name: コマンド実行
      ansible.builtin.shell:
        cmd: exec bash
      changed_when: no
      register: execution_result

    - name: コマンド実行結果の確認
      ansible.builtin.debug:
        var: execution_result

    - name: vimrcファイルをコピー
      ansible.builtin.copy:
        src: ./files/vimrc
        dest: /home/isucon/.vimrc

    - name: tarファイルの解凍
      ansible.builtin.unarchive:
        src: ./files/alp_linux_amd64.tar
        dest: /tmp
        remote_src: yes

    - name: alpのインストール
      ansible.builtin.shell:
        cmd: install /tmp/alp_linux_amd64 /usr/local/bin/alp
      changed_when: no
      register: execution_result

    - name: コマンド実行結果の確認
      ansible.builtin.debug:
        var: execution_result

