- hosts: all
  tasks:
    - name: .bashrcに追記
      ansible.builtin.blockinfile:
        path: /home/isucon/.bashrc
        block: "{{item}}"
        insertafter: EOF
        state: present
      with_file:
        - files/bashrc_prompt.txt

    - name: bash_profileファイルをコピー
      ansible.builtin.copy:
        src: ./files/bash_profile
        dest: /home/isucon/.bash_profile

    - name: vimrcファイルをコピー
      ansible.builtin.copy:
        src: ./files/vimrc
        dest: /home/isucon/.vimrc

